### ISSUE TITLE
Feature Request: Adding a search bar

### ISSUE THREAD

**Issue by Thanatoz-1** [dgraph-io/hugo-dgraph-theme#6]
There is no option for searching the blogs for a required post. Could you please add this feature.?

**Comment by paulftw** [comment]
We've recently added taxonomy support, that may address search for smaller blogs.

Not likely to add search soon, because that'd require... I'm not even sure what that'd require - will probably need an external indexing server?

Closing this bug for now, but as always, upvotes here and pull requests are welcome if you want to help adding the search feature.
