### ISSUE TITLE
Theme's exampleSite directory was deleted

### ISSUE THREAD

**Issue by onedrawingperday** [dgraph-io/hugo-dgraph-theme#7]
Hello @paulftw 

I am one of the maintainers of the Hugo Themes repository.

In commit https://github.com/dgraph-io/hugo-dgraph-theme/commit/cb69c267857e77fb9b1f3e4c5ebea62c6329fcdb you deleted the exampleSite of your theme and as a result your theme demo no longer generates.

If you no longer wish to have an exampleSite then you need to test your theme with the [HugoBasicExample](https://github.com/gohugoio/hugoBasicExample/)

ref: https://github.com/gohugoio/hugoThemes/issues/531

cc: @digitalcraftsman

**Comment by paulftw** [comment]
Hi @onedrawingperday, thanks for getting in touch and thanks for doing the hard work of maintaining this great project.

Although hugo-dgraph-theme is open source it is not maintained for general purpose use - we built it for our blog and as we aren't designers I don't think it's good enough to be useful to others out-of-the-box.

We welcome anyone to fork it and do whatever the current license (MIT) permits, but providing support for external builds is something I don't have resources for.

I deleted the exampleSite because someone raised an issue that it was broken, and I didn't want to mislead anyone into thinking that exampleSite is maintained.

We test our theme every time we update our blog and that's been good enough for now.
With HugoBasicExample I'm not even sure where to start integrating it.

**Can you recommend a low maintenance approach to keep the theme in the gallery or could you just drop it from there?**

**Comment by onedrawingperday** [comment]
>Can you recommend a low maintenance approach to keep the theme in the gallery or could you just drop it from there?

We can add this theme to the `noDemo` list of the Build Script so that it doesn't throw errors during deployment.

I will send a PR to the Hugo Themes repo. If it's accepted I will let you know.

**Comment by onedrawingperday** [comment]
The PR to add this theme in the `noDemo` array of the Hugo Themes Site Build Script was merged earlier.

**Comment by manishrjain** [comment]
Hey guys,

I'm a big fan of Hugo. I'm not sure how much work is it, but @paulftw if you can fix up the issues and make it workable, I'd like the theme to be featured the same way as it was before.

Thanks for letting us know, @onedrawingperday . We'll get back with some update and direction.

**Comment by onedrawingperday** [comment]
@manishrjain 

When is merged it will be possible to have your theme's demo published once again on the Hugo website.

However the [logo](https://github.com/dgraph-io/hugo-dgraph-theme/commit/cb69c267857e77fb9b1f3e4c5ebea62c6329fcdb#diff-6c2af3bb1c1809ea1ccc8875f04833a7) in the header will be 404 because your associates deleted the exampleSite.

You really need to revert commit https://github.com/dgraph-io/hugo-dgraph-theme/commit/cb69c267857e77fb9b1f3e4c5ebea62c6329fcdb#diff-6c2af3bb1c1809ea1ccc8875f04833a7 for your theme's demo to appear as it was before.

Let me know once this issue is addressed so that I can remove your theme from the `noDemo` array of the Hugo Themes Site Build Script.

**Comment by paulftw** [comment]
Hey @onedrawingperday I've put the ExampleSite back and also tested the theme with the HugoBasicExample you've linked when opening the issue.

**Is this enough to fully re-enable our theme in the gallery?**

Please let me know what else I can do to improve presentation and make it more useful.

**Comment by onedrawingperday** [comment]
@paulftw Thank you for issuing a fix to this issue. There is nothing more that needs to be done from your part.

Once https://github.com/gohugoio/hugoThemes/pull/591 is merged in the Hugo Themes repo and themes are updated the DGraph theme demo will generate on the Hugo website once again as it was except for its content that is inherited from the [HugoBasicExample](https://github.com/gohugoio/hugoBasicExample/tree/master/content) due to https://github.com/gohugoio/hugoThemes/pull/547

I'm closing this issue as it is fixed.
